Made components border radius to use css variables.
epicmaxco/vuestic-ui pull request #1134
Opened 2021-09-23 14:08 UTC by m0ksem

## Description
Unified borders:
```css
  --va-border-radius-sm: 0.25rem;
  --va-border-radius-md: 0.375rem;
  --va-border-radius-lg: 0.5rem;
  --va-border-radius-circle: 50%;
  --va-border-radius-circle-fixed: 100rem;
```

Removed such border-radiuses as 0.2rem, 0.3rem, 0.4rem, because they are not integral numbers.

Also use `--va-border-radius-circle-fixed: 100rem` which makes rounded corners for any size bottom (lower than 100rem which is impossible to have)

Please help me to review all these changes. Something can be broken.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2021-09-30 14:49 UTC, asvae commented on packages/ui/src/components/va-alert/_variables.scss
> -:root {
Deletion of this file doesn't seem intended to me.

2021-09-30 14:49 UTC, asvae commented on packages/ui/src/components/va-alert/_variables.scss
> -:root {
😿 

![image](https://user-images.githubusercontent.com/5394573/135478418-eff0c6e2-4f7c-4378-9647-40425da98d29.png)

2021-09-30 14:53 UTC, asvae commented on packages/ui/src/components/va-app-bar/VaAppBar.demo.vue
> +  border-radius: var(--va-border-radius);
Doesn't seem to be declared anywhere, so unlikely to work.
`--va-border-radius`

2021-09-30 14:55 UTC, asvae commented on packages/ui/src/components/va-popup/popup/VaPopup.vue
> -<script>
Doesn't appear to be part of this MR?

2021-09-30 15:00 UTC, asvae commented on packages/ui/src/components/va-timeline/VaTimelineSeparator/_variables.scss
> -:root {
PRobably also not intended?

2021-09-30 15:01 UTC, asvae requested changes
Looks pretty dangerous, removes a bunch of random stuff.
Border related changes look fine to me though.

2021-10-06 08:41 UTC, m0ksem commented
Looks like I need to update this PR with current HEAD. :(

2022-02-07 20:58 UTC, m0ksem commented
This PR requires a lot of QA 😅

2022-08-27 12:39 UTC, m0ksem commented
Moved to another task.

2022-08-27 12:39 UTC, closed without merging