Feature/hint message color
epicmaxco/vuestic-ui pull request #1424
Opened 2022-01-18 15:20 UTC by LighthouseKeeperYN

## Description

## Markup:

<details>

```vue
// Your code
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-01-18 15:40 UTC, m0ksem requested changes
Thanks, please notice my suggestion.

2022-01-18 15:40 UTC, m0ksem commented on packages/ui/src/components/va-input/components/VaInputWrapper.vue
> +      <slot name="messages" />
Let user completely redefine messages look. Please, check if VaMessageList is exposed in vuestic-ui.

```suggestion
      <slot name="messages" v-bind="{ messages: messagesComputed, errorLimit, color: messagesColor }">
            <va-message-list
                :color="messagesColor"
                :model-value="messagesComputed"
                :limit="errorLimit"
              />
      </slot>
```

2022-01-18 16:37 UTC, m0ksem approved these changes

2022-01-19 13:05 UTC, RVitaly1978 reviewed
Looks good.
Please, add `VaMessageList` to `src/vuestic-plugin/vuestic-components.ts`

2022-01-19 21:04 UTC, asvae commented on packages/ui/src/components/va-input/_variables.scss
> +  --va-message-list-color: (--va-gray);
var skipped :)
--va-message-list-color: var(--va-gray);

2022-01-19 21:21 UTC, asvae commented on packages/ui/src/components/va-input/components/VaInputWrapper.vue
> +    vertical-align: middle;
Just curious, what's this for? :)

2022-01-19 21:21 UTC, asvae approved these changes
Thanks! Great work.
Feel free to merge once you're happy with state.

2022-01-20 17:47 UTC, merged