refactor:  packages\ui\src\components\va-affix\VaAffix.vue
epicmaxco/vuestic-ui pull request #1442
Opened 2022-01-24 14:39 UTC by LighthouseKeeperYN

#1397

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-01-25 03:57 UTC, m0ksem requested changes

2022-01-25 03:57 UTC, m0ksem commented on packages/ui/src/components/va-affix/VaAffix.vue
> +        console.log(props.offsetTop)
```suggestion
```

2022-01-25 03:57 UTC, m0ksem commented on packages/ui/src/components/va-affix/VaAffix.vue
> +      bottom: state.value.isBottomAffixed ? convertToPixels(calculateBottom) : null,
Better ts typing for CSSProperties type.

```suggestion
      top: state.value.isTopAffixed ? convertToPixels(calculateTop) : undefined,
      bottom: state.value.isBottomAffixed ? convertToPixels(calculateBottom) : undefined,
```

2022-01-26 07:47 UTC, RVitaly1978 requested changes
Looks good!
Pay attention to one remark.

2022-01-26 12:48 UTC, LighthouseKeeperYN commented on packages/ui/src/components/va-affix/VaAffix.vue
>          const scrollBarHeight = offsetHeight - clientHeight
fixed

2022-01-26 12:58 UTC, RVitaly1978 approved these changes

2022-01-27 09:07 UTC, merged