custom drag n drop label text
epicmaxco/vuestic-ui pull request #1615
Opened 2022-04-01 15:20 UTC by aluarius

close: #1596 

## Description
Added optional props for custom drag'n'drop label text.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-04-04 10:38 UTC, m0ksem reviewed
I think we also want to care about "Upload file" text here. Also, would be nice to have slots here, maybe. 

https://github.com/epicmaxco/vuestic-ui/blob/ec2c65ce510f285606f381573bbb63e4baa1c33e/packages/ui/src/components/va-file-upload/VaFileUpload.vue#L14-L25

2022-04-04 14:02 UTC, aluarius commented
> I think we also want to care about "Upload file" text here. Also, would be nice to have slots here, maybe.

Agree, slots looks fine here.

2022-04-04 15:09 UTC, Derranion approved these changes
Thanks,

Could you please add this to the docs description.

Because otherwise users will not know how to use it without checking source code.

[Here are some slots examples in our docs](https://vuestic.dev/en/ui-elements/select#slots).

2022-04-04 16:48 UTC, m0ksem requested changes

2022-04-04 16:48 UTC, m0ksem commented on packages/ui/src/components/va-file-upload/VaFileUpload.vue
> +        <slot name="dropZoneLabel">Drag’n’drop files or</slot>
Having prop for label is more appropriate. We can use [Components Config]( https://vuestic.dev/en/services/components-config) for i18n for all components :) 

When I spoke about slot, I meant a slot that can be used to change overall file-upload visual (to replace default button and label text). Sorry for that. Let's better have props that can be changed in global config.

2022-04-05 11:29 UTC, aluarius commented
Added props for custom upload button & drop zone. Added slot for the whole upload area (no v-bind for events needed, cause there is hidden input, covering the whole area). Added examples and docs description.

2022-04-05 12:11 UTC, m0ksem approved these changes
Pretty nice now 😊

2022-04-06 00:36 UTC, Derranion approved these changes

2022-04-06 08:31 UTC, merged