Fix/1597 outdated docs examples
epicmaxco/vuestic-ui pull request #1619
Opened 2022-04-04 09:41 UTC by aluarius

close: #1597

## Description
All docs examples were checked. Mentioned files are not forgotten - they're outdated, linked to the components or props, that are not existing. For examle, va-color-input-advanced component, selected props for va-color-input or mode props for va-date-input.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-04-04 10:32 UTC, m0ksem commented
Let's have this on hold. We will need to copy-paste these changes to nuxt docs later...

2022-04-04 12:33 UTC, Derranion requested changes
These docs examples are not outdated.

For instance we have `mode` property in the `va-date-input` but this example is not used in the `page-config` of our docs page.

It will look this way, when we add them:

![addDocsExamples](https://user-images.githubusercontent.com/7745899/161544102-60304677-2bda-4cc4-9619-bfd49048b29f.jpg)


This means that we need to add these files to the related pages and add some description:
- [ ] Check if examples are working correctly.
- [ ] Add these examples to the page configs.

2022-04-04 13:50 UTC, aluarius commented
@Derranion thank you, i've understood about mode.vue. But what about other files? Not existing components va-color-input-advanced, va-color-palette-advanced, va-color-picker, va-color-slider.

For example, i see va-color-input-advanced call in VaColorInput.vdemo.vue, but that part of code commented since 2020.

Or select props, which is not existing both component code and docs (ve checked one more time).

2022-05-12 11:39 UTC, rustem-nasyrov approved these changes

2022-05-13 11:07 UTC, RVitaly1978 approved these changes

2022-05-13 11:08 UTC, merged