[#1625] Fix breadcrumbs router error
epicmaxco/vuestic-ui pull request #1627
Opened 2022-04-05 11:39 UTC by RVitaly1978

## Description
close #1625

changes:
- [x] fix `isDisabled` in `VaBreadcrumbsItem` and component minor updates
- [x] use `ExtractPropType` in `useRouterLink`
- [x] add comment `/** @deprecated */` to mixins

![chrome-capture](https://user-images.githubusercontent.com/55198465/161745382-c66e9e9d-e6de-4e8c-bfdf-5d40c8e5f9a2.gif)
![chrome-capture (1)](https://user-images.githubusercontent.com/55198465/161745481-ee93aab3-e5fa-4ed9-b9d9-34606e345baa.gif)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-04-05 12:21 UTC, m0ksem approved these changes

2022-04-05 13:39 UTC, aluarius approved these changes

2022-04-05 13:59 UTC, Derranion approved these changes

2022-04-05 23:46 UTC, Derranion requested changes
If we will try to navigate from the `...localhost/en/ui-elements/breadcrumbs` to any other `docs` page we will receive this error:

![i18n_error](https://user-images.githubusercontent.com/7745899/161865563-ecdbdbc8-3a5c-4f95-801a-a61dde5b771a.jpg)

Most likely caused by this [Vue bug](https://github.com/intlify/vue-i18n-next/issues/412) - update to `3.0.10` version may help.

Though we need to test it, new version may also add some TS errors but this should be manageable.

2022-04-06 07:54 UTC, m0ksem commented
> If we will try to navigate from the `...localhost/en/ui-elements/breadcrumbs` to any other `docs` page we will receive this error:
> 
> ![i18n_error](https://user-images.githubusercontent.com/7745899/161865563-ecdbdbc8-3a5c-4f95-801a-a61dde5b771a.jpg)
> 
> Most likely caused by this [Vue bug](https://github.com/intlify/vue-i18n-next/issues/412) - update to `3.0.10` version may help.
> 
> Though we need to test it, new version may also add some TS errors but this should be manageable.

Yap. You can find more info here: https://github.com/epicmaxco/vuestic-ui/pull/1627/files#diff-02ef34fd350e2b5fc1ae6a62c3354e0b6fc335bff0c2e7e5f078c2eda5962a82

This issue closed 11 months ago in v3.1.0 [Changelog](https://github.com/vuejs/core/blob/main/CHANGELOG.md#bug-fixes-41). We can update vuestic's minimal vue version to 3.1.0. @asvae

2022-04-06 12:18 UTC, rustem-nasyrov approved these changes

2022-04-07 13:05 UTC, merged