[Feature] add undo prop to VAFileUpload
epicmaxco/vuestic-ui pull request #1744
Opened 2022-05-08 07:42 UTC by eyuelberga

## Description

close #1735

**Note** : 
After merging this commit 8449e357ce4948d76f048aef69aa7a6a140075a0 some components stopped working properly including `VAFileUpload`.  It is related to `shallowReadonly`. I have noticed this on `VaAccordion`, `VaCheckbox`, `VaCollapse`.

This is the warning that comes up on the console:

```
​Set operation on key "modelValue" failed: target is readonly. Proxy
set @ reactivity.esm-bundler.js:545
```
I didn't create an issue because the commit is in the develop branch

## Markup:

<details>

```vue
// Your code
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-05-10 07:25 UTC, RVitaly1978 requested changes

2022-05-10 07:25 UTC, RVitaly1978 commented on packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
> +  </template>
```suggestion
    <va-file-upload-undo
      v-if="undo"
      class="va-file-upload-gallery-item--undo"
      @recover="recoverImage"
    />
```

2022-05-10 07:25 UTC, RVitaly1978 commented on packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue
> +  </template>
```
<va-file-upload-undo
  v-if="removed && undo"
  @recover="recoverFile"
/>
```

2022-05-10 10:13 UTC, RVitaly1978 approved these changes

2022-05-13 21:25 UTC, m0ksem approved these changes
How about having undo button under X button? 
![image](https://user-images.githubusercontent.com/23530004/168391328-a47930d2-120b-492d-a76e-86ae114f887d.png)


Also, would be nice to have undoTimeout prop. Or choose better name.
It is hard for me in 2sec to move touchpad to undo button 😂, count that I need to think 1.5sec.

P.S. you can see on paint screenshot I need to move touchpad 3 times to get "undo" button.

2022-05-15 14:30 UTC, eyuelberga commented
I have added an `undoDuration` prop to adjust the undo timeout

2022-05-16 06:58 UTC, RVitaly1978 approved these changes

2022-05-16 09:18 UTC, m0ksem approved these changes
Thanks! 🎉

2022-05-16 10:08 UTC, aluarius approved these changes

2022-05-16 13:37 UTC, merged