`VaAccordion` open-close behavior fix
epicmaxco/vuestic-ui pull request #1757
Opened 2022-05-11 14:19 UTC by aluarius

## Description
Closed `VaCollapse` click in `VaAccordion` should close the opened one and open the clicked one (previously closed item click just closed the opened one). Related naming fixes.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-05-12 17:58 UTC, m0ksem requested changes

2022-05-12 17:58 UTC, m0ksem commented on packages/ui/src/components/va-collapse/VaCollapse.vue
> +    }
```suggestion
```

2022-05-12 17:58 UTC, m0ksem commented on packages/ui/src/components/va-accordion/hooks/useAccordion.ts
> +  watch(state, () => { if (directToggle.value) { accordion.onItemChanged(item) } })
```suggestion
  const toggle = () => {
    state.value = !state.value
    accordion.onItemChanged(item)
  }
```

2022-05-13 10:34 UTC, RVitaly1978 approved these changes

2022-05-13 11:21 UTC, m0ksem approved these changes

2022-05-13 11:21 UTC, m0ksem commented on packages/ui/src/components/va-accordion/hooks/useAccordion.ts
> +    toggle: () => {
Simple function names usually require comments.

```suggestion
    /** Toggle collapse value and notify accordion about it */ 
    toggle: () => {
```

2022-05-13 13:46 UTC, merged