Fix release 1.4.0 bugs
epicmaxco/vuestic-ui pull request #1777
Opened 2022-05-14 13:07 UTC by RVitaly1978

## Description
related to #1765

- [x] import `va-icon` in `va-collapse`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-05-14 15:06 UTC, m0ksem commented
Already fixed here: https://github.com/epicmaxco/vuestic-ui/pull/1769/files#diff-db4b1867556df714c7f323554d3b4d8b5a576bf02231974629f77d9ce7dd06db

2022-05-16 10:45 UTC, aluarius approved these changes
Much more cleare templates, thanks!)

2022-05-17 10:46 UTC, m0ksem requested changes
![firefox_o3vVizRCGz](https://user-images.githubusercontent.com/23530004/168794038-c53dbb4b-9f45-44bc-8d7d-9dfd1bae6a32.gif)

Doesn't work for me.

2022-05-17 10:53 UTC, m0ksem approved these changes

2022-05-17 10:54 UTC, merged