[#1545] rollup changed to vite, css split added
epicmaxco/vuestic-ui pull request #1801
Opened 2022-05-18 14:58 UTC by aluarius

close: #1545 
close: #1646 

## Description
Rollup production build has been fully changed to Vite (`yarn build` to test it). CSS spliting added (for ESM build, including import to separate components).

New average build time is 27 s (vs previous 156 s for my pc).

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-05-18 15:38 UTC, aluarius commented
- [ ] delete build:rollup in the end of pr.

2022-05-18 18:43 UTC, rustem-nasyrov requested changes

2022-05-18 18:43 UTC, rustem-nasyrov commented on packages/ui/build/vite/build.mjs
> +} from "fs";
Use here a single quote.

2022-05-18 18:43 UTC, rustem-nasyrov commented on packages/ui/build/vite/build.mjs
> +    }).join('')
```suggestion
    const componentName = folderName.split('-').map((el) => el.charAt(0).toUpperCase() + el.slice(1)).join('')
```

2022-05-18 18:43 UTC, rustem-nasyrov commented on packages/ui/build/vite/build.mjs
> +    existsSync(filePath) && renameSync(filePath, newFilePath)
I think you can check `existsSync(filePath)`, and then inside of the `if` assign new variable and call `renameSync` function.

2022-05-18 18:43 UTC, rustem-nasyrov commented on packages/ui/build/vite/build.mjs
> +  if (isEmpty) {
`isEmpty` variable is redundant.

2022-05-18 18:43 UTC, rustem-nasyrov commented on packages/ui/build/vite/configs/vite.esm.js
> +  const format = 'esm'
I think here the `format` variable is redundant (in the other configuration files too).

2022-05-19 08:20 UTC, RVitaly1978 approved these changes

2022-05-19 17:57 UTC, m0ksem commented
@aluarius, FYI, please don't merge it ASAP. Let us make some patch releases before this feature will be merged.

I will review it later 👍

2022-05-19 21:47 UTC, m0ksem commented
CSS bundles: {
 `vuestic/css` - for cjs, iife - all CSS, for esm - all CSS without components CSS (need to be tested)
      L for esm build components styles must be imported in component
 `vuestic/essential.css` - only essential styles
 `vuestic/components.css` - all component styles without typography, grid, reset etc.
 `vuestic/styles/[typography, grid, reset, etc]` - just css of this pacakges.
}

Faced issue right now. We have component styles only in /css, it makes unable user to use only component styles and essential CSS.

2022-05-20 21:22 UTC, m0ksem approved these changes
I like it! 😊 But let's have it on hold for a while.

2022-06-02 20:29 UTC, Derranion approved these changes

2022-07-14 13:23 UTC, aluarius commented
Moved to https://github.com/epicmaxco/vuestic-ui/pull/2081

2022-07-14 13:23 UTC, closed without merging