fix: carrousel demo slots wrong name
epicmaxco/vuestic-ui pull request #1813
Opened 2022-05-19 13:07 UTC by edimitchel

## Description

The demo with slots is using wrong slots names.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-05-19 14:27 UTC, RVitaly1978 approved these changes

2022-05-19 17:54 UTC, m0ksem requested changes
lol, this typo is not in demo, rather in component.

https://github.com/epicmaxco/vuestic-ui/blob/98607ba52e4bdbb60117e8aeadc4f63b8e6e70ea/packages/ui/src/components/va-carousel/VaCarousel.vue#L27

Can I ask you to update VaCarousel as well?

2022-05-19 22:02 UTC, edimitchel commented
Done!

2022-05-20 06:43 UTC, RVitaly1978 approved these changes

2022-05-20 13:29 UTC, m0ksem approved these changes
Thanks! 😊

2022-05-20 13:29 UTC, merged