[#1752] Modal padding and Content improvements
epicmaxco/vuestic-ui pull request #1928
Opened 2022-06-10 07:46 UTC by damirJa

Fix #1752
## Description
- Added padding variables to manage padding
- Added `no-padding` prop
- Added `content` slot which replace all the content inside `va-modal__inner`

- Removed hardcoded paddings and this could brake some of the users code, not sure how to resolve it
```
  $modal-padding-top: 1.25rem !default;
  $modal-padding-right: 1.875rem !default;
  $modal-padding-bottom: 1.5rem !default;
  $modal-padding-left: 1.5rem !default;
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-06-10 07:56 UTC, m0ksem approved these changes
👍

2022-06-10 07:56 UTC, m0ksem commented on packages/ui/src/components/va-modal/VaModal.vue
> +      'va-modal--noPadding': props.noPadding,
```suggestion
      'va-modal--no-padding': props.noPadding,
```

2022-06-10 13:04 UTC, RVitaly1978 requested changes
Could you also add new information about props and slots to the docs?

2022-06-10 13:04 UTC, RVitaly1978 commented on packages/ui/src/components/va-modal/VaModal.demo.vue
> +        <div>{{ message }}</div>
```suggestion
        {{ message }}
```

2022-06-10 13:24 UTC, m0ksem commented on packages/ui/src/styles/resources/_variables.scss
>  $zindex-modal: 1050 !default;
Would suggest making it in another PR.

2022-06-16 12:17 UTC, m0ksem commented
Added docs about this feature.
![image](https://user-images.githubusercontent.com/23530004/174067691-ce167c93-3acc-4497-a429-70b82f9006d0.png)
![image](https://user-images.githubusercontent.com/23530004/174067666-73e9592c-67f6-47d9-b1c1-26634aa55291.png)

2022-06-16 14:08 UTC, damirJa commented
Thanks for catch up on this

2022-06-21 08:14 UTC, RVitaly1978 approved these changes

2022-06-22 10:31 UTC, merged