Feat/popover slots rework
epicmaxco/vuestic-ui pull request #1980
Opened 2022-06-22 10:22 UTC by rustem-nasyrov

Close: #1649

## Description
Added slots to the popover component, examples of its usage. Added translations. Refactored component.

![image](https://user-images.githubusercontent.com/29167241/175006231-e129ead5-635f-408b-9166-7d99f6843cd6.png)

Refactored and beautified vue-book demo example:
![image](https://user-images.githubusercontent.com/29167241/175006543-4d1189eb-4a40-46ac-bde8-0dea28240c2e.png)

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-06-22 10:28 UTC, m0ksem approved these changes

2022-06-22 12:22 UTC, aluarius approved these changes

2022-06-22 12:46 UTC, RVitaly1978 requested changes

2022-06-22 12:46 UTC, RVitaly1978 commented on packages/docs/src/locales/en/en.json
> +        "body": " Custom body slot"
```suggestion
        "body": "Custom body slot"
```

2022-06-22 12:46 UTC, RVitaly1978 commented on packages/docs/src/locales/ru/ru.json
> +        "body": " Слот для контента компонента"
```suggestion
        "body": "Слот для контента компонента"
```

2022-06-22 12:46 UTC, RVitaly1978 commented on packages/docs/src/page-configs/ui-elements/popover/examples/Slots.vue
> +</script>
```suggestion
```

2022-06-22 12:46 UTC, RVitaly1978 commented on packages/ui/src/components/va-popover/VaPopover.demo.vue
>                <va-button>Right</va-button>
```suggestion
              placement="left"
              message="Placement Left"
              class="mr-4"
            >
              <va-button>Left</va-button>
```
and the same below

2022-06-22 12:46 UTC, RVitaly1978 commented on packages/ui/src/components/va-popover/VaPopover.vue
> +import VaIcon from '../va-icon/VaIcon.vue'
```suggestion
import { VaDropdown } from '../va-dropdown'
import { VaIcon } from '../va-icon'
```

2022-06-22 12:46 UTC, RVitaly1978 commented on packages/ui/src/components/va-popover/_variables.scss
> +  --va-popover-body-line-height: 1.5rem;
```suggestion
  --va-popover-body-line-height: 1.5;
```

2022-06-22 12:46 UTC, RVitaly1978 commented on packages/ui/src/components/va-popover/_variables.scss
> +  --va-popover-content-background-color: #ffffff;
```suggestion
  --va-popover-content-background-color: var(--va-white);
```

2022-06-23 06:32 UTC, RVitaly1978 approved these changes

2022-06-23 07:01 UTC, merged