Fix incorrectly applied progress bar height (#1950)
epicmaxco/vuestic-ui pull request #1981
Opened 2022-06-22 10:38 UTC by smellyshovel

Resolves #1950 

What it used to look like:
![image](https://user-images.githubusercontent.com/9782236/175009198-602cf1e7-5eaa-4cbf-a992-8a1d54119ff8.png)

What it looks like with the fix applied:
![image](https://user-images.githubusercontent.com/9782236/175009344-defedd37-6ce2-4bb4-9e31-7736eba3961d.png)

The issue was in that the `height` was applied to the whole block (including the slotted content) whereas it should be applied only to the progress bar's wrapper.

2022-06-22 13:12 UTC, RVitaly1978 requested changes

2022-06-22 13:12 UTC, RVitaly1978 commented on packages/ui/src/components/va-progress-bar/VaProgressBar.vue
>        })),
this class must be in the root wrapper

2022-06-22 13:52 UTC, smellyshovel commented on packages/ui/src/components/va-progress-bar/VaProgressBar.vue
>        })),
Fair point, will be addressed.

2022-06-22 14:30 UTC, smellyshovel commented on packages/ui/src/components/va-progress-bar/VaProgressBar.vue
>        })),
Resolved via 96f8f5e

2022-06-23 06:33 UTC, RVitaly1978 approved these changes

2022-06-23 15:03 UTC, m0ksem approved these changes

2022-06-23 16:16 UTC, merged