Fix#2028/fix sidebar color
epicmaxco/vuestic-ui pull request #2041
Opened 2022-07-04 17:23 UTC by m0ksem

closes #2028

Fix sidebar item colors until 1.5.0. 

Also, hide sidebar title if minimized, instead of making it opacity: 0.

Another breaking change is minimizedWidth set to 4rem from 2.5rem.

This changes looks like Okay?

2022-07-05 06:49 UTC, RVitaly1978 approved these changes

2022-07-05 06:49 UTC, RVitaly1978 commented on packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
> +        return getColor(getColor(props.activeColor))
```suggestion
        return getColor(props.activeColor)
```

2022-07-05 07:04 UTC, aluarius approved these changes

2022-07-05 09:48 UTC, RVitaly1978 commented
I didn't see a solution of the issue #1959

2022-07-05 11:12 UTC, m0ksem commented
> I didn't see a solution of the issue #1959

> right: implementation weird when minimized and user have to set position: absolute

Is fixed here. For top, bottom I suggest just remove this prop types. It's a Sidebar, not Navbar.

2022-07-07 07:22 UTC, RVitaly1978 requested changes
- icons jump
![chrome-capture-2022-6-7 (2)](https://user-images.githubusercontent.com/55198465/177714263-cfa32640-b4b4-4288-8847-474233adf05d.gif)

- what color behavior should be?
![chrome-capture-2022-6-7 (3)](https://user-images.githubusercontent.com/55198465/177714912-98e9ce09-33d4-4e7a-98a2-98d045793eec.gif)

- wierd doc sidebar
![chrome-capture-2022-6-7 (4)](https://user-images.githubusercontent.com/55198465/177715571-3dad194f-1d8c-45e1-99fb-f9ed40377e5b.gif)

2022-07-07 16:06 UTC, aluarius approved these changes

2022-07-07 16:10 UTC, m0ksem commented on packages/ui/src/components/va-collapse/VaCollapse.vue
> +          attributes: headerAttributes,
I'm not sure which name is better. 
v-bind="bind"

or v-bind="attributes"

:)))

Likely bind, we can add listeners here.

2022-07-07 18:35 UTC, merged