[#2057] `VaDateInput` & `VaTimeInput` moved to `VaInputWrapper`, refactoring, bugfix
epicmaxco/vuestic-ui pull request #2107
Opened 2022-07-15 09:13 UTC by aluarius

Close: #2057 

## Description
- [x] `VaDateInput` & `VaTimeInput` moved to `VaInputWrapper` from `VaInput`.
- [x] Fixed related tabindex problems (for example, user was able to focus icons-buttons despite of readonly state).
- [x] Fixed manual date input bug. In case of American locale on the computer, string `02.01.2000` will be parsed (via `Date.parse`) as `01 Feb 2000` (not `02 Jan 2000`) and string `15.07.2000` will throw an error (there is no 15 month).
- [x] Fixed readonly/disabled/manual-input state issues (for example, user was able to open date/time picker despite of disabled state or user was't able to focus component by click for manual input - dropdown was opening).
- [x] Accessibility fixes.
- [x] Related minor refactoring.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-07-18 14:07 UTC, RVitaly1978 commented on packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
> +    ...useClearableProps,
why do we need it?

2022-07-18 14:20 UTC, RVitaly1978 commented on packages/ui/src/components/va-time-input/VaTimeInput.vue
>        rules: [],
the same as above

2022-07-19 12:26 UTC, RVitaly1978 requested changes

2022-07-19 12:26 UTC, RVitaly1978 commented on packages/ui/src/components/va-date-input/VaDateInput.vue
> +    placeholder: { type: String, default: '' },
```suggestion
```
it can be passed as an attribute

2022-07-19 12:26 UTC, RVitaly1978 commented on packages/ui/src/components/va-date-input/VaDateInput.vue
> +const VaInputWrapperProps = extractComponentProps(VaInputWrapper, ['focused', 'maxLength', 'counterValue'])
```suggestion
const VaInputWrapperProps = extractComponentProps(VaInputWrapper, ['requiredMark', 'focused', 'maxLength', 'counterValue'])
```

2022-07-19 12:26 UTC, RVitaly1978 commented on packages/ui/src/components/va-date-input/VaDateInput.vue
> +    }))
```suggestion
      ...validationAriaAttributes.value,
      ...omit(attrs, ['class', 'style']),
    }))
```

2022-07-19 12:26 UTC, RVitaly1978 commented on packages/ui/src/components/va-date-input/VaDateInput.vue
> +      ...omit(attrs, ['class', 'style']),
```suggestion
      requiredMark: attrs.required,
```

2022-07-19 12:26 UTC, RVitaly1978 commented on packages/ui/src/components/va-time-input/VaTimeInput.vue
> +const VaInputWrapperProps = extractComponentProps(VaInputWrapper, ['focused', 'maxLength', 'counterValue'])
the same as in `va-date-input`

2022-07-19 13:37 UTC, rustem-nasyrov approved these changes

2022-07-19 14:27 UTC, RVitaly1978 approved these changes

2022-07-21 17:18 UTC, m0ksem approved these changes

2022-07-21 17:19 UTC, merged