feat(dropdown): prevent-overflow prop.
epicmaxco/vuestic-ui pull request #2154
Opened 2022-07-25 22:00 UTC by m0ksem

It is not actually the optimization I wanted to make, but it makes dropdown lag less, because of position relative. I don't actually know how this thing can be optimized... Profiler shows "OK", like, vue takes more time to mount component then we render dropdowns. We 100% must always have DOMRect to reactively react on some changes, like placement changes, etc. We could make useFloatingPopover and usePopover and make `prevent-overflow` prop non-reactive. 

Probably issue like on [this video ](https://github.com/epicmaxco/vuestic-ui/pull/2109#pullrequestreview-1043569748) has been fixed because I removed unnecessary width css property setting in keepAnchorWidth block, which tirgger browser re-render while we inside requestAnimationFrame two times with some JS execution between.

2022-07-27 19:50 UTC, m0ksem commented
@RVitaly1978, take a look. I moved all keyboard navigation from TimeInput, DateInput and Select directly to Dropdown.

2022-07-28 07:43 UTC, RVitaly1978 commented
some issues:
1) in all components (`TimeInput`, `DateInput` and `Select`):
![chrome-capture-2022-6-28](https://user-images.githubusercontent.com/55198465/181445542-df8519e8-9407-4e45-8a1d-577b684b4610.gif)

2) `va-time-input` with `manual-input` prop doesn't open dropdown by up/down arrows (only by clicking on icon)

3) no cursor `pointer` when hovering over icon `va-time-input`
![chrome-capture-2022-6-28 (1)](https://user-images.githubusercontent.com/55198465/181446920-d59cd10c-8e06-4fae-aeb7-34a63beaea46.gif)

4) weird cursor when hovering over `va-date-input`
![chrome-capture-2022-6-28 (2)](https://user-images.githubusercontent.com/55198465/181447335-3af1e04d-6d9c-49ae-b81e-0d7ecec5a2f9.gif)

5) while va-date-input has display: flex and a bug with setting the CSS `width` rule, we can have some fun:
![chrome-capture-2022-6-28 (3)](https://user-images.githubusercontent.com/55198465/181448323-02174e73-4064-4d7d-8a2f-acbba75838bb.gif)

6) and also we have to do something (perhaps in a different issue) with our `va-dropdown` `disabled` behavior because we have a double opacity setting in the `disabled` components (`TimeInput`, `DateInput` and `Select` ):
<img width="346" alt="image" src="https://user-images.githubusercontent.com/55198465/181449248-84760c5f-a637-4975-8d17-2dbd1ce92137.png">

2022-07-28 15:20 UTC, RVitaly1978 requested changes

2022-07-28 15:22 UTC, m0ksem commented on packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
> +  },
It is actually easier to write them here :)

2022-07-28 20:53 UTC, merged