fixed roadmap responsiveness on mobile
epicmaxco/vuestic-ui pull request #2186
Opened 2022-07-30 14:45 UTC by ameer-khan-ashraf

Close #2183 

## Description
Added two media query in the roadmap.vue file to fix the roadmap in mobile view

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-07-31 20:44 UTC, m0ksem requested changes
Thanks!

I would suggest you make these columns responsive to any screen size, instead of anchoring to a specific screen size.

Having flex-wrap will move column that not fit downside, flex 1 will force column to take as much space as it can, and min width will force columns to be readable and move other columns to down.

2022-07-31 20:44 UTC, m0ksem commented on packages/docs/src/page-configs/introduction/roadmap/components/roadmap.vue
> +        }
```suggestion
    .docs-roadmap__column {
      &-wrapper {
        width: 100%;
        min-width: 300px;
        flex: 1;
        padding: calc($gap / 2);
```

2022-07-31 20:44 UTC, m0ksem commented on packages/docs/src/page-configs/introduction/roadmap/components/roadmap.vue
> +    }
```suggestion
    display: flex;
    flex-wrap: wrap;
    width: 100%;
```

2022-08-01 06:00 UTC, ameer-khan-ashraf commented
Thanks for the heads up. I have updated the code and pushed another commit.

2022-08-01 10:30 UTC, m0ksem approved these changes

2022-08-01 10:30 UTC, merged