[#1808] Swipable `VaCarousel`
epicmaxco/vuestic-ui pull request #2366
Opened 2022-09-07 14:11 UTC by aluarius

Closes: #1808 

## Description
Swiping composable + integration to `VaCarousel`.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-09-09 13:53 UTC, m0ksem approved these changes
![Bruh](https://user-images.githubusercontent.com/23530004/189365285-17513520-5f8c-4606-b80e-a3d4bf8f32fb.gif)

Have issue with `user-select`. Would be nice to have `useUnselectable` :D

Also, for me, swipe feels too sensitive... Would be nice if I need to make more effort for swipe. This just unnatural.

2022-09-09 13:53 UTC, m0ksem commented on packages/ui/src/composables/useSwipe.ts
> +      if (Math.abs(xDistance) > Math.abs(yDistance) && isSwipeAllowed.value.horizontal) {
Would be nice to have `reactiveComputed` to change it to isSwipeAllowed.horizontal

2022-09-09 13:53 UTC, m0ksem commented on packages/ui/src/composables/useSwipe.ts
> +  const isSwipeAllowed = computed(() => ({
Or having isHorizontalSwipeAllowed

2022-09-14 06:29 UTC, RVitaly1978 requested changes

2022-09-14 06:29 UTC, RVitaly1978 commented on packages/ui/src/composables/useSwipe.ts
> +      } else if (isSwipeAllowed.vertical) {
why do we check the condition `Math.abs(xDistance) > Math.abs(yDistance)` on line 120 and don't check the condition on line 123 accordingly?

2022-09-14 06:29 UTC, RVitaly1978 commented on packages/ui/src/composables/useSwipe.ts
> +  watch(swipeState, cb, { deep: true })
```suggestion
  watch(swipeState, () => cb(swipeState.direction), { deep: true })
```

2022-09-14 06:29 UTC, RVitaly1978 commented on packages/ui/src/composables/useSwipe.ts
> +  })
This variable isn't used

2022-09-14 13:59 UTC, merged