make VaPagination bg color transparent as in VaInput
epicmaxco/vuestic-ui pull request #2559
Opened 2022-10-23 19:20 UTC by Azgiliat

Close #2507

2022-10-24 08:19 UTC, rustem-nasyrov requested changes

2022-10-24 08:19 UTC, rustem-nasyrov commented on packages/ui/src/components/va-pagination/VaPagination.vue
> +    background-color: transparent;
```suggestion
    background-color: var(--va-pagination-input-background);
```
where:
```
--va-pagination-input-background: var(--va-background-primary);
```

2022-10-25 07:40 UTC, m0ksem approved these changes
Apply Rustem's suggestion.

2022-10-25 16:05 UTC, rustem-nasyrov approved these changes

2022-10-25 16:07 UTC, merged