[#1180] `VaDataTable` grid mode
epicmaxco/vuestic-ui pull request #2797
Opened 2022-12-16 12:06 UTC by aluarius

Close: #1180 
Close: #2338  

## Description
- [x] added grid view mode;
- [x] docs updates;
- [x] refactoring;
- [x] minor bugfixing (have faced several old bugs). 

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/64714442/208094597-172813bc-26ff-493d-bd4f-5a34a20754aa.png">

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-12-19 14:41 UTC, rustem-nasyrov requested changes
Great, but still things to do. Also, I'll check functionality a bit later.

2022-12-19 14:41 UTC, rustem-nasyrov commented on packages/ui/src/components/va-data-table/hooks/useCommonProps.ts
> +export const items = { items: { type: Array as PropType<DataTableItem[]>, default: () => [] as DataTableItem[] } }
This kind of naming might mislead. Would be better to name props like others in the `VaDataTable` component. For example `useDataTableItems`.

2022-12-19 14:41 UTC, rustem-nasyrov commented on packages/ui/src/components/va-data-table/hooks/useTableScroll.ts
>  ) {
```suggestion
export const useTableScroll = (
  props: ExtractPropTypes<typeof useTableScrollProps>,
  emit: (event: 'scroll:bottom' | 'scroll:top', ...args: any[]) => void,
) => {
```

2022-12-19 14:41 UTC, rustem-nasyrov commented on packages/ui/src/components/va-data-table/hooks/useStylable.ts
> +export function useStylable (props: ExtractPropTypes<typeof useStylableProps>) {
```suggestion
export const useStylable = (props: ExtractPropTypes<typeof useStylableProps>) => {
```

2022-12-19 14:41 UTC, rustem-nasyrov commented on packages/ui/src/components/va-data-table/hooks/usePaginatedRows.ts
>  ) {
```suggestion
export const usePaginatedRows = (
  sortedRows: Ref<DataTableRow[]>,
  props: ExtractPropTypes<typeof usePaginatedRowsProps>,
) => {

2022-12-19 14:41 UTC, rustem-nasyrov commented on packages/ui/src/components/va-data-table/hooks/useAnimationName.ts
>  ) {
```suggestion
export const useAnimationName = (
  props: ExtractPropTypes<typeof useAnimationNameProps>,
  rows: Ref<DataTableRow[]>,
) => {
```

2022-12-20 05:18 UTC, aluarius commented on packages/ui/src/components/va-data-table/components/VaDataTableThRow.vue
> +import { VaCheckbox } from '../../va-checkbox'
It ruins precommit check.

2023-01-05 15:25 UTC, m0ksem requested changes
![image](https://user-images.githubusercontent.com/23530004/210816233-357aff0f-516a-4eea-8440-ba6c492ef4fb.png)

As I understand gird can be helpful in mobile, but....

Add breakpoints here

2023-01-06 06:19 UTC, m0ksem commented
```css
--va-data-table-grid-count: unset

@media for mobile {
  --va-actual-data-table-grid-count: var(--va-data-table-grid-count, 2)
}

@media for desktop{
  --va-actual-data-table-grid-count: var(--va-data-table-grid-count, 4)
}
```

2023-01-09 09:16 UTC, rustem-nasyrov approved these changes

2023-01-30 13:56 UTC, m0ksem commented
I don't think it closes https://github.com/epicmaxco/vuestic-ui/issues/2338

2023-01-30 13:57 UTC, merged