`VaSelect` updates and refactoring
epicmaxco/vuestic-ui pull request #2803
Opened 2022-12-20 04:38 UTC by aluarius

Close: #2673 
Close: #2795 

## Description
- [x] added `max-visible-options` prop to limit the output inside of input wrapper;
- [x] added `selected-top-shown` prop to show selected options at the top of the options list;
- [x] refactoring. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-12-20 10:34 UTC, rustem-nasyrov requested changes
Great! But here a few suggestions.

2022-12-20 10:34 UTC, rustem-nasyrov commented on packages/ui/src/components/va-select/VaSelect.vue
>  import { VaInput, VaInputWrapper } from '../va-input'
```suggestion
import {
  VaDropdown,
  VaDropdownContent,
  VaBadge,
  VaIcon,
  VaInput,
  VaInputWrapper,
} from '../index'
```

2022-12-20 10:34 UTC, rustem-nasyrov commented on packages/ui/src/components/va-select/hooks/useMaxVisibleOptions.ts
> +  props: ExtractPropTypes<typeof useMaxVisibleOptionsProps> & { multiple: boolean, modelValue: SelectOption | SelectOption[] },
Imo, will be better to move to the separate type and use it here.

2022-12-20 10:34 UTC, rustem-nasyrov commented on packages/ui/src/components/va-select/hooks/useMaxVisibleOptions.ts
> +  const { modelValue } = toRefs(props)
If here no plans to make another props reactive, then will be great to use `toRef()`.

2022-12-20 10:34 UTC, rustem-nasyrov commented on packages/docs/src/locales/en/en.json
> +        "title": "Max visible selected options amount",
```suggestion
        "title": "Max visible selected options",
```

2022-12-20 10:34 UTC, rustem-nasyrov commented
<img width="290" alt="image" src="https://user-images.githubusercontent.com/29167241/208646540-17a8f06a-3722-4aae-be20-b1a0b5e89d5e.png">
Can we improve this?

2022-12-20 10:35 UTC, rustem-nasyrov commented
Also, would be great to have demos in the vue-book.

2022-12-21 02:48 UTC, aluarius commented
> Also, would be great to have demos in the vue-book.

We already have it:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/64714442/208808852-8a9e4c7c-b0df-4bc3-83b6-a58a97902c83.png">

2022-12-21 03:27 UTC, aluarius commented
> Can we improve this?

Will implement nowrap class for this case.

2022-12-26 09:16 UTC, rustem-nasyrov approved these changes

2023-01-05 14:56 UTC, m0ksem approved these changes

2023-01-05 14:58 UTC, merged