`usePlacementAliases` refactor and `useDeprecated` bugfix
epicmaxco/vuestic-ui pull request #2804
Opened 2022-12-20 08:31 UTC by aluarius

## Description
- [x] `useDeprecated` composable fix (not proper worked with props).
- [x] `usePlacementAliases` (mostly types).

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2022-12-20 11:50 UTC, rustem-nasyrov commented on packages/ui/src/composables/usePlacementAliases.ts
> +type PlacementAlias = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'left-top' | 'right-top' | 'left-bottom' | 'right-bottom'
Isn't possible to replace this like in #8 line below?

2022-12-20 11:50 UTC, rustem-nasyrov commented on packages/ui/src/composables/usePlacementAliases.ts
> +const xPlacementPosition: XPlacementPosition[] = ['left', 'right']
Can be named as `verticalPlacement`/`horizontalPlacement`. But it's for your discretion.

2022-12-21 11:37 UTC, rustem-nasyrov requested changes
Facing issues with auto placement on the scroll. You can check it on the date-picker page for example.

2022-12-21 13:22 UTC, rustem-nasyrov commented
I don't know is it problem with dropdown or time picker component configuration, but I'm facing this bug. When you open focus on time picker component and scroll up, it automatically positionates to the center.
Before scrolling:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/29167241/208915087-e37b845d-20d7-4b91-9faa-92fbcd451769.png">
After:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/29167241/208915144-60658907-9a69-46fe-8fbc-f753169aaea9.png">

2022-12-22 02:35 UTC, aluarius commented
@rustem-nasyrov this behaviour is not related to this pr, because our prod site also contains it. But yeah, it looks like a bug, will move it to the separate issue.

2022-12-22 07:50 UTC, rustem-nasyrov approved these changes

2022-12-23 04:24 UTC, merged