fix: replace navbar static height with paddings, fix: mobile layout
epicmaxco/vuestic-ui pull request #2835
Opened 2023-01-03 13:45 UTC by LighthouseKeeperYN

I changed navbar height to be defined by padding rather than height so it can expand instead of overflowing and fixed a couple of layout bugs.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2023-01-04 14:06 UTC, LighthouseKeeperYN commented on packages/ui/src/components/va-navbar/VaNavbar.vue
> -  height: var(--va-navbar-height);
You can already do it by applying single line of css. I don't think there's a need for dedicated prop.

2023-01-04 14:31 UTC, LighthouseKeeperYN commented on packages/ui/src/components/va-navbar/VaNavbar.vue
> +  justify-content: space-between;
Check again please.

2023-01-05 11:47 UTC, rustem-nasyrov requested changes
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/29167241/210773447-b1ce20fc-0c92-47f3-bd2b-e02e96102dec.png">

2023-01-10 09:15 UTC, rustem-nasyrov approved these changes

2023-01-11 15:15 UTC, m0ksem approved these changes

2023-01-11 15:16 UTC, merged