Feat/2869 image viewer
epicmaxco/vuestic-ui pull request #2886
Opened 2023-01-23 12:52 UTC by aluarius

Closes: #2869

Blocked by: https://github.com/epicmaxco/vuestic-ui/pull/2868

## Description
`VaViewer` component. Extends VaImage. In the future discussed with Maxim to make it much more universal.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2023-01-27 09:31 UTC, rustem-nasyrov approved these changes
LGTM.
- Are you planning to add docs page for this component?
<details>
<summary>Controls</summary>
Is it planned that controls div is over image?
<img width="789" alt="image" src="https://user-images.githubusercontent.com/29167241/215053166-6363947c-242e-4ec9-968a-b38c81e4f581.png">
</details>

2023-01-27 09:36 UTC, aluarius commented
> Are you planning to add docs page for this component?

Me and Maxim decided not to add this components to our docs until it'll become complete.

> Is it planned that controls div is over image?

Yes, i have used Ant Design as an example for the controls. They also have them in this way.

2023-01-30 11:35 UTC, m0ksem requested changes

2023-01-30 11:35 UTC, m0ksem commented on packages/ui/src/components/va-viewer/VaViewer.demo.vue
> +        <template #anchor="{ openViewer, isOpened }">
Let's say that. If there is no default slot, we use anchor and image slots. If there is default slot, we  use default slot as anchor and image.

So there is a simple interface:
```vue
<va-viewer><va-image/></va-viewer>
```

or a bit complicated:
```vue
va viewer
  va button #anchor="{ show }" @click="show"
  va image #image
```

2023-01-30 11:35 UTC, m0ksem commented on packages/ui/src/components/va-viewer/VaViewer.demo.vue
> +          style="--va-image-position: relative;"
I think va-viewer should do this automatically.

2023-02-08 12:52 UTC, m0ksem approved these changes

2023-02-08 12:52 UTC, m0ksem commented on packages/ui/src/components/va-viewer/VaViewer.vue
> +    class="va-viewer__anchor"
redundant div?

2023-02-08 12:52 UTC, m0ksem commented on packages/ui/src/components/va-viewer/VaViewer.vue
> +      @click="openViewer"
This must be .va-viewer

2023-02-08 12:52 UTC, m0ksem commented on packages/ui/src/components/va-viewer/VaViewer.vue
> +      @click="openViewer"
This must be `.va-viewer-content` (not `.va-viewer__content`, because it is not a child component)

2023-02-10 12:55 UTC, merged