[#2989] [#2990] Tailwind & VaAspactRatio docs pages, related bugfix
epicmaxco/vuestic-ui pull request #3000
Opened 2023-02-16 10:34 UTC by aluarius

Closes: #2989 
Closes: #2990 

## Description
- [x] Tailwind docs page;
- [x] VaAspectRatio docs page;
- [x] VaAspectRatio added to @vuestic/nuxt components list;
- [x] Vuestic UI build type error fix.  

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

2023-02-16 11:11 UTC, m0ksem requested changes
Minor issues

2023-02-16 11:11 UTC, m0ksem commented on packages/ui/src/components/va-select/components/VaSelectContent/VaSelectContent.vue
> +    value: { type: Array as PropType<SelectOption[]>, default: [] as SelectOption[] },
Mustn't it be handled with useStateful composable? Even though, if it is internal component, I would better use `required: true` here.

2023-02-16 11:11 UTC, m0ksem commented on packages/docs/page-config/ui-elements/aspect-ratio/index.ts
> +    block.example("Default", { hideTitle: true }),
Example block will render titles automatically, if not, you have a wrong structure in locales file.

```suggestion
    block.example("Default"),
```

2023-02-16 11:11 UTC, m0ksem commented on packages/docs/page-config/ui-elements/aspect-ratio/index.ts
> +    block.example("WithOtherComponents", { hideTitle: true }),
```suggestion
    block.example("WithOtherComponents"),
```

2023-02-16 11:11 UTC, m0ksem commented on packages/docs/page-config/styles/tailwind/code/configuringFull.ts
> +// main.*
Hm. We could get rid of these comments and provide fileName options for block.code.

2023-02-16 15:36 UTC, m0ksem requested changes

2023-02-16 15:36 UTC, m0ksem commented on packages/docs/locales/en.json
> +    "tailwind": "Tailwind Support",
```suggestion
    "tailwind": "Tailwind Integration",
```

2023-02-16 15:38 UTC, m0ksem commented
And I would reorder styles page:

- Colors
- CSS Variables
- Typography
- GrId (Make alert in grid and say that we recommend use Tailwind)
- Tailwind Integration
- Smart Helpers
- CSS reset (Make alert that we will remove it, because components work great without reset).

2023-02-17 07:34 UTC, aluarius commented
> And I would reorder styles nav menu

Let's make it here https://github.com/epicmaxco/vuestic-ui/issues/2823

2023-02-17 15:47 UTC, m0ksem approved these changes

2023-02-17 15:47 UTC, merged