Feature/expandable row
epicmaxco/vuestic-ui pull request #3054
Opened 2023-02-23 16:10 UTC by LighthouseKeeperYN

close #2837

Adds expandable row for data table.

Breaking changes: cell slot bindings were changed from `cell` to `{ cell, row }`. `row `property is necessary to access expandable row trigger.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

![image](https://user-images.githubusercontent.com/47790197/220963691-af3d4c61-74f4-4702-8f6d-78d889b43883.png)

2023-02-24 13:57 UTC, m0ksem requested changes
Looks cool. 

Found few issues: 
- No collapse animation (expand animation looks good)
- Missing --expanded classes. It is a normal practice to add some background to an expanded row, people must have classes for it. For example:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/23530004/221196025-f019e737-550c-4292-b5a0-25d88efb4985.png">

2023-02-24 15:58 UTC, aluarius requested changes
Smthng happens for `VaDataTable.new.demo.vue`. It worked before, so, something goes wrong.

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/64714442/221225631-d74e0a52-4636-4e9d-a9e4-507b26fe1a77.png">

2023-03-01 11:03 UTC, m0ksem approved these changes
I changed demo a bit, so it looks a bit interesting:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/23530004/222121430-46f84396-296b-4fc4-a79f-023186d93031.png">

Also, I moved back rowData to slot binds and added it to expandableRow.

2023-03-01 11:06 UTC, m0ksem commented on packages/ui/src/components/va-data-table/VaDataTable.vue
> +                  class="va-data-table__table-tr--expanded va-data-table__table-expanded-content"
Also, classes here are important to have, because likely user want table to be customizable.

2023-03-01 11:06 UTC, m0ksem commented on packages/ui/src/components/va-data-table/hooks/useRows.ts
> +    rowData: source,
Alias to rowData, so it has the same API as DataTableCell

2023-03-01 12:10 UTC, aluarius approved these changes

2023-03-01 12:20 UTC, merged