Docs/i18n split
epicmaxco/vuestic-ui pull request #3073
Opened 2023-02-25 21:37 UTC by m0ksem

Split translations for docs.
<img width="171" alt="image" src="https://user-images.githubusercontent.com/23530004/221380669-cb06ab30-e76f-4fb9-b4a7-96b62b86dd76.png">

And testing docs in one PR:
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/23530004/221380658-19bde62d-0730-494a-9c7a-04b102ec4b1e.png">

2023-02-25 22:04 UTC, m0ksem commented
Maybe gonna add a TS support here and store translations in one file after discussion.

2023-02-27 22:26 UTC, m0ksem commented
Decided not to make a TS support and prefer separated files instead.

2023-03-01 22:25 UTC, asvae requested changes
Local version is somewhat broken.

2023-03-01 22:25 UTC, asvae commented on packages/docs/locales/en.json
>      "i18n": "I18n",
Some translations look to be broken:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/5394573/222278534-68f02210-35f7-4e2e-bfc8-9c6f1f30bedd.png">

2023-03-04 13:19 UTC, merged