feat: add gravatar usage example
epicmaxco/vuestic-ui pull request #3094
Opened 2023-02-27 17:15 UTC by rustem-nasyrov

Close #2663 

<img width="516" alt="image" src="https://user-images.githubusercontent.com/29167241/221632697-1e7b39db-eda1-4c6d-a399-5cc8be1eb8c1.png">

## Description
- Gravatar usage examples.
- Default fallback with global config.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2023-02-28 07:52 UTC, aluarius approved these changes

2023-02-28 13:26 UTC, asvae commented
Maybe we can use some email (maybe of evan or posva?).
As that's what example is trying to show, not the fact that VaImage accepts image.

https://en.gravatar.com/site/implement/hash/
If it's too hard - let's drop the idea and use your current implementation.

2023-02-28 13:46 UTC, asvae requested changes
commented

2023-03-01 20:36 UTC, asvae approved these changes
Cool!

2023-03-02 07:37 UTC, merged