Feat/forms
epicmaxco/vuestic-ui pull request #3224
Opened 2023-03-23 13:02 UTC by m0ksem

closes #2117

New Features:

- [x] Form Data
```vue
<template>
  <va-form ref="myForm" stateful class="mb-2 flex flex-col gap-2">
    <va-input name="firstName" label="First Name" />
    <va-input name="lastName" label="Last Name" />
    <va-date-input name="birthDay" label="Birth day" />
  </va-form>

  <ul>
    <li>First name: {{ formData.firstName }}</li>
    <li>Last name: {{ formData.lastName }}</li>
    <li>Birth day: {{ formData.birthDay }}</li>
  </ul>
</template>

<script setup lang="ts">
  import { useForm } from 'vuestic-ui'

  const { formData } = useForm('myForm')
</script>
```

- [x] Named Errors:
```vue
<template>
  <va-form immediate hide-error-messages ref="myForm" class="flex flex-col gap-2 mb-2">
    <va-input
      label="Login"
      v-model="form.login"
      name="Login"
      :rules="[(v) => Boolean(v) || 'Login is required']"
    />
    <va-input
      label="Password"
      v-model="form.password"
      type="password"
      name="Password"
      :rules="[
        (v) => Boolean(v) || 'Password is required',
        (v) => v.length > 6 || 'Password must be a least 6 symbols',
      ]"
    />
  </va-form>

  <div v-for="errors, fieldName in errorMessagesNamed" :key="fieldName">
    <span class="va-title" v-if="errors.length > 0">{{ fieldName }}</span>
    <ul>
      <li v-for="error in errors" :key="error">
        {{ error }}
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { useForm } from "vuestic-ui";

const form = reactive({
  login: "",
  password: "",
});

const { errorMessagesNamed } = useForm("myForm");
</script>
```

- [x] Fixed reset methods

- [ ] Async Validation

2023-03-23 13:09 UTC, m0ksem commented
Let's check if anybody has some thoughts about extending VaForm features or simplify current features.

2023-03-30 08:42 UTC, RVitaly1978 approved these changes

2023-03-30 14:58 UTC, rustem-nasyrov requested changes

2023-03-30 14:58 UTC, rustem-nasyrov commented on packages/ui/src/components/va-form/VaFormNew.demo.vue
> +        />
After selecting and removing selection, validation didn't happen.

2023-03-30 14:58 UTC, rustem-nasyrov commented on packages/ui/src/composables/useForm/useFormParent.ts
> +import { computed, provide, ref, Ref } from 'vue'
```suggestion
import { computed, provide, ref, type Ref } from 'vue'
```

2023-03-30 14:58 UTC, rustem-nasyrov commented on packages/ui/src/composables/useForm/useFormParent.ts
> +      return results.every((result) => result)
https://github.com/epicmaxco/vuestic-ui/pull/3224/files#r1152851712 (Boolean trick).

2023-04-03 12:02 UTC, m0ksem commented on packages/ui/src/composables/useForm/useFormParent.ts
> +      fields.value[uid] = field
Nope, because vue has _uid attached to each component which is always a uniq value. App id is also used in case user have multiple apps.

2023-04-03 17:21 UTC, rustem-nasyrov commented on packages/docs/page-config/ui-elements/form/examples/Default.vue
Never mind one of the commits fixed it. :)

2023-04-03 17:21 UTC, rustem-nasyrov commented on packages/ui/src/components/va-form/VaFormNew.demo.vue
> +        />
Fixed.

2023-04-11 21:24 UTC, merged