[#3304] Redesign `Vuestic` landing
epicmaxco/vuestic-ui pull request #3340
Opened 2023-04-17 16:50 UTC by RVitaly1978

## Description
close #3304
close #3347 

- [x] update `landing` page
- [x] update `overview` page
- [x] fix `landing.vue` and `default.vue` nuxt layouts

<details>
<summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/55198465/232554381-86e45a57-69e1-4ea3-ae74-14914a03cd12.png)

![image](https://user-images.githubusercontent.com/55198465/232554476-0c8f19f2-70de-4152-9559-fec5af9f6e44.png)

![image](https://user-images.githubusercontent.com/55198465/232554542-5b9fc063-cd01-4d57-aa4a-5e21e4b5a7c7.png)

https://user-images.githubusercontent.com/55198465/232555101-7d01d32d-af7f-4b05-b3ae-81eb13cb944b.mov

</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2023-04-17 16:59 UTC, zvenigorodskaia approved these changes

2023-04-17 19:26 UTC, m0ksem requested changes

2023-04-17 19:26 UTC, m0ksem commented on packages/docs/components/landing/Preview.vue
> +          <va-image
Wouldn't recommend to use va-image in nuxt app. It still have some SSR issues. Change it to img and ratio wrapper. For me, in both build and dev images are not visible.

2023-04-18 11:32 UTC, m0ksem commented
- contrast issue in partners block:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/23530004/232752204-62543eb2-cb44-4a14-ab5c-d9fe2bae12b9.png">

- IE icons seems inappropriate
<img width="254" alt="image" src="https://user-images.githubusercontent.com/23530004/232752506-97c5aa0e-efe9-48d1-94df-5625ec260445.png">

While we have blue as accent color, it feels strange to have purple icons  
     
 Hand drawn icons feel inappropriate when all other design looks formal.   
    
Text also not relevant. IMO "Support modern browsers" mean nothing, wondering if there are frameworks that support only old browsers lol. "No IE, sorry" also old and must be removed because it makes no sense (every vue3 framework do not support IE11 and it is not modern browser). I would change it to "responsive" only.  
  
As a developer I will be interested in Developer Experience, SSR support, Keyboard Navigation and integration with other things like AgGrid, Tailwind, UnoCss, (maybe Laravel, rich text editors - we don't have this for now), etc. I change features list to:

Accessible & keyboard navigation support
    - SSR friendly
    - Focused on DX
    - Integration with i18n, tailwind and more
  

- "Customize everything" "Get started" button should redirect to some page related to customization. Perhaps we need some "Customization guide" page.
<img width="728" alt="image" src="https://user-images.githubusercontent.com/23530004/232760347-b1675dfa-c511-4847-8667-b6e12609f0b1.png">

- Overall, "Features" and "Customize Everything" look so much different from other sections. 


Btw, first section looks perfect!

2023-04-18 11:47 UTC, m0ksem commented
@zvenigorodskaia, we must merge this PR in develop when it is completed. If you're going to review this, please, run project locally. Otherwise, the incomplete landing page will appear in production with tiny releases someday. For example, I've just fixed the form demos and if we merge this PR before, it would have ended up in production.

2023-04-20 15:05 UTC, merged