Remove translations
epicmaxco/vuestic-ui pull request #3451
Opened 2023-05-29 22:54 UTC by misterpekert

closes #3425

Still WIP

2023-06-14 15:58 UTC, asvae requested changes
Couple of small things to finish, but very close to done. Great work!

I went through all functional files, and randomly checked about 10% of page-config pages.

2023-06-14 15:58 UTC, asvae commented on packages/docs/components/layout/LanguageDropdown.vue
Can't we remove language dropdown altogether?

2023-06-14 15:58 UTC, asvae commented on packages/docs/modules/page-config/blocks/api/index.vue
> +          text: getTranslation('slots', key) + '. ' + getTranslation('slots', 'scopeAvailable'),
Same here. (shouldn't be called `getTranslation`)

2023-06-14 15:58 UTC, asvae commented on packages/docs/modules/page-config/blocks/list/index.vue
> +const mark = (translations: string[]): string => {
These are not translations?

2023-06-14 15:58 UTC, asvae commented on packages/docs/modules/page-config/blocks/shared/code/useCode.ts
> +// export const useCode = () => {
Let's remove it. Was useful before, not now.

2023-06-14 15:58 UTC, asvae commented on packages/docs/modules/page-config/i18n/export-translations.ts
> +  console.log(translations);
Console.log )

2023-06-14 15:58 UTC, asvae commented on packages/docs/page-config/ui-elements/toast/api-description.ts
> +export default {
We can use define function here similar to `defineManualApi`. That way we'll have proper typing.

2023-06-14 15:58 UTC, asvae commented on packages/docs/pages/[page-config-category]/[page].vue
> +// const mergeTranslations = () => {
Let's remove these comments.

2023-06-15 14:09 UTC, misterpekert commented on packages/docs/README.md
>  without Tailwind.
Those used as code examples on `services/i18n` page

2023-06-15 18:29 UTC, asvae commented on packages/docs/page-config/ui-elements/affix/index.ts
> +    block.api("VaAffix", defineApiDescription({
Probably not needed here. TS can derive type from `block.api` argument typing.

2023-06-16 09:01 UTC, merged