feat(VaTreeView): add selected node class
epicmaxco/vuestic-ui pull request #3464
Opened 2023-06-02 02:38 UTC by mengqiuleo

closes[#3456 ](https://github.com/epicmaxco/vuestic-ui/issues/3456)

add active property in treeNodeClassComputed, and control `active` with `selectedNodeComputed.value === props.node.id`,
add style for active class.

## Description

active class style is consistent with hover style

## Markup:

<details>

```vue
const treeNodeClassComputed = useBem('va-tree-node', () => ({
     disabled: !!props.node.disabled,
     active: selectedNodeComputed.value === props.node.id,
 }))
```

```scss
  &--active > &-root::before {
    border-radius: var(--va-tree-node-border-radius);
    opacity: var(--va-tree-node-interactive-bg-opacity);
  }
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2023-06-05 15:20 UTC, m0ksem requested changes

2023-06-06 02:34 UTC, mengqiuleo commented on packages/ui/src/components/va-tree-view/components/VaTreeNode/VaTreeNode.vue
> +      active: selectedNodeComputed.value === props.node.id,
selectedNodeComputed records the id of the currently selected node.
The code for selectedNodeComputed is here. [selectedNodeComputed](https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/components/va-tree-view/hooks/useTreeView.ts#LL56C1-L56C1)
So,  I use whether the id of the current node is consistent with selectedNodeComputed. If true, it means that the node is active.

Do I need to use the `selected` property instead?


If want to use the `selected` property, code maybe looks like this.
```js
const treeNodeClassComputed = useBem('va-tree-node', () => ({
      disabled: !!props.node.disabled,
      active: !!props.node.selected,
 }))

// when this node is clicked (each node has an onNodeClick event)
const onNodeClick = () => {
    toggleSelectNode(props.node) // todo: change selected property
}
```

In toggleSelectNode, we need to set the selected state of the current node and ensure that other nodes are not selected.
This seems to be more complicated than selectedNodeComputed.

By the way, selectedNodeComputed not only saves the current selected node, but also will trigger the update-selected method in set. However, the description of update-selected in the doc is blank at present. I can create a doc issue and solve it.

2023-06-06 02:37 UTC, mengqiuleo commented on packages/ui/src/components/va-tree-view/components/VaTreeNode/VaTreeNode.vue
> +      active: selectedNodeComputed.value === props.node.id,
doc: https://ui.vuestic.dev/en/ui-elements/tree-view#events

2023-06-20 00:34 UTC, m0ksem commented on packages/ui/src/components/va-tree-view/components/VaTreeNode/VaTreeNode.vue
> +      active: selectedNodeComputed.value === props.node.id,
I think `selectedNodeComputed` is something old... There at least might be many nodes selected, not only one. `selectedNodeComputed` stores one id, but what if there are two nodes selected? I think we need to depend on node.checked. I also can not see applied class when I select a node. I added few modifier classes to tree-node, please double-check if it work as expected.

2023-06-22 09:18 UTC, m0ksem approved these changes

2023-06-22 09:19 UTC, m0ksem commented
I'll merge this PR to include in next release, we can extend it later if needed.

2023-06-22 09:20 UTC, merged

2023-07-11 14:05 UTC, codeonmoon commented
@m0ksem - Could you please let us know how to use this merged feature?

2024-05-16 06:58 UTC, raizdev commented
I see this is implemented? @m0ksem how can I use this feature? I don't see active class in the DOM for selectedNodes