docs: fix fonts loading
epicmaxco/vuestic-ui pull request #3492
Opened 2023-06-12 20:17 UTC by m0ksem

Improved FCP and overall lighthouse score.
<img width="781" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/edb9ddab-8614-4f0d-972a-1e3224ddad6b">

2023-06-12 20:20 UTC, m0ksem commented
@zvenigorodskaia. I'll need a PNG image of preview-features.svg. SVG is 600kb, png is 60kb or 20kb compressed with https://tinypng.com

2023-06-19 17:51 UTC, asvae requested changes
I did some checking and:

Lighthouse gives pretty much identical results (you can check https://ui-experimental.vuestic.dev and https://ui-develop.vuestic.dev/)
<img width="541" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/166fb437-d17d-4b11-854a-f4febc286ebc">
<img width="527" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/96303f11-39c3-4b91-a855-bc7b25fd4f6f">

Performance tests also didn't show any significant advantage:
<img width="412" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/6494f4bf-2421-433d-b5f6-f342fcafb9b6">
<img width="412" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/5e73c2ea-cec9-481a-b29d-225f2bdd99a6">

For both cases I did about 5 tests and number were pretty similar. So I'm not sure if we improved anything performance wise.

What I noticed is that there is much less screen permutations, which is a good thing. There was only one left - two times fonts are updated (for components and across the page):
![screencast 2023-06-19 21-47-47](https://github.com/epicmaxco/vuestic-ui/assets/5394573/6b4a66a7-78b4-4fe3-9342-784ae0d6d3e9)

Also icon disappeared:
![image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/7c2772cc-c496-41c6-a129-43ff841eb2fa)

2023-06-20 10:59 UTC, m0ksem commented
Must be ok now:
<img width="1643" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/91703974-7518-4730-a935-9e8f9a2bd03a">

2023-06-21 10:47 UTC, asvae approved these changes

2023-06-21 10:47 UTC, merged