feat: add VaDropdown keepAnchorHeight property (#3083)
epicmaxco/vuestic-ui pull request #3501
Opened 2023-06-16 15:57 UTC by ilearnjs

Add VaDropdown keepAnchorHeight property 

## Description

Add new property for VaDropdown which fixes the problem when dropdown height is larger than viewport or VaDropdown  target
For more details see video here https://github.com/epicmaxco/vuestic-ui/issues/3083

## Markup:

<details>

```vue
// Your code
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2023-06-19 17:37 UTC, ilearnjs commented on packages/ui/src/components/va-dropdown/hooks/useDropdown.ts
> +  console.log('placementComputed', placementComputed.value)
```suggestion
```

2023-06-19 17:37 UTC, ilearnjs commented on packages/ui/src/components/va-dropdown/hooks/useDropdown.ts
> +
```suggestion
```

2023-06-20 01:03 UTC, m0ksem requested changes
Maybe rename prop to `takeAvaialbeHeight`. Or maybe make it as default behavior and name prop like `ignoreAvailableHeight` that will be used to disable this behavior.

You also need to rebase branch with develop and cherry-pick your commits. Because we squash commits there will be duplicated code changed.

2023-06-20 13:47 UTC, ilearnjs commented on packages/docs/page-config/ui-elements/dropdown/api-description.ts
> +    keepAnchorHeight: "If true, dropdown content will adjust its height when the content is larger than available space",
Renamed to `verticalScrollOnOverflow`

2023-06-20 14:05 UTC, ilearnjs commented
Moved here https://github.com/epicmaxco/vuestic-ui/pull/3501

2023-06-20 14:05 UTC, closed without merging