fix(ui): select, date-input, time-input keyboard navigation
epicmaxco/vuestic-ui pull request #3523
Opened 2023-06-22 09:02 UTC by m0ksem

Previously it was impossible to open select, date-input, time-input with space and enter for some reason.

2023-06-22 20:16 UTC, asvae requested changes
Checked locally - there are some issues.

2023-06-22 20:16 UTC, asvae commented on packages/ui/src/components/va-date-input/VaDateInput.vue
>  const VaInputWrapperProps = extractComponentProps(VaInputWrapper, ['focused', 'maxLength', 'counterValue'])
<img width="461" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/888b6d78-1bf8-4558-a147-7655cd8369ca">

Date input doesn't close on click outside.

2023-06-22 20:16 UTC, asvae commented on packages/ui/src/components/va-date-input/VaDateInput.vue
>  const VaInputWrapperProps = extractComponentProps(VaInputWrapper, ['focused', 'maxLength', 'counterValue'])
Same issue for time input

<img width="385" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/e2c8879e-62b0-4f50-8e7f-20ab1b94faab">

2023-07-01 00:00 UTC, pogrib0k requested changes
I looked it up like everything is ok.
But `DateInput` allows focus outside the component, so sometimes something like this happens:
![image](https://github.com/epicmaxco/vuestic-ui/assets/58943459/53e3ceb9-b866-4de2-b736-b159574157ee)

Also, because of this, I can open many "dropdowns" at the same time (see screenshot), and when I press **ESC** they all close at the same time.
![image](https://github.com/epicmaxco/vuestic-ui/assets/58943459/532e5be9-3464-4277-9282-3c1e981ba981)

2023-07-06 11:09 UTC, ilearnjs approved these changes

2023-07-06 11:21 UTC, merged