raw: layout
epicmaxco/vuestic-ui pull request #3633
Opened 2023-07-24 20:59 UTC by m0ksem

closes https://github.com/epicmaxco/vuestic-ui/issues/1430

Features:
- [x] New component: VaLayout
- [x] top, bottom, left, right slots
- [x] order
- [x] animations support
- [x] absolute areas
- [x] mobile friendly
- [x] docs and examples

Default:
<img width="919" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/de8d7a19-7d61-4b44-87b3-6e1c0c78c8a1">

Order:
<img width="921" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/12086a76-60e3-471d-9579-11630db4fab5">

Absolute:
<img width="919" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/953ad0c2-9f49-4cec-9c44-8d2e8b61315a">

2023-07-31 18:57 UTC, asvae requested changes
Found a couple of bugs.

I checked experimental.

2023-07-31 18:57 UTC, asvae commented on packages/docs/page-config/ui-elements/layout/index.ts
> +VaLayout component is used in pair with [VaSidebar](/ui-elements/sidebar)[[target=_blank]], [VaNavbar](/ui-elements/navbar)[[target=_blank]] components.
```suggestion
VaLayout component could be used in pair with [VaSidebar](/ui-elements/sidebar)[[target=_blank]], [VaNavbar](/ui-elements/navbar)[[target=_blank]] components.
```

2023-07-31 18:57 UTC, asvae commented on packages/docs/page-config/ui-elements/navbar/examples/Default.vue
> +    <template #center>
Menu button does nothing:

<img width="394" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/287a370b-a1cc-4fc9-a671-2c5172111ae3">

2023-07-31 18:57 UTC, asvae commented on packages/docs/page-config/ui-elements/layout/examples/AllSlots.vue
> +<template>
Would be nice to have something that looks all right on mobile:

<img width="428" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/ce6a23af-2fc1-435d-b8cc-8dfed2b50175">

2023-07-31 18:57 UTC, asvae commented on packages/docs/page-config/ui-elements/layout/examples/Order.vue
> +<script setup lang="ts">
Also would be nice to have a plausible mobile example.

<img width="680" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/21173867-3835-47ca-846a-d7df177c50df">

Maybe we can just make sidebars proportional on mobile?

2023-08-19 20:24 UTC, m0ksem commented
Wondering if we want to improve Navbar so it can have shadow and bordered class.

Also, looks like having VaFooter (the same as Sidebar, but with top shadow and border) will be a huge DX improvement.

2023-08-24 10:32 UTC, asvae commented
Moved story issue here - #3734

2023-08-24 10:40 UTC, asvae commented on packages/docs/page-config/ui-elements/layout/examples/Default.vue
> +<script setup lang="ts">
Text eloped

![image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/d7e0032b-2983-4139-91c2-a9855353638f)

2023-08-31 12:20 UTC, asvae commented
@m0ksem button visual bug is still relevant

I suggest we create a button with right 5rem or so, so that it doesn't overlap with close.
We also probably want to make this button have white half-transparent background and make it stick on scroll.

<img width="558" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/76eec29f-1ec2-47f3-aae8-881e655efb34">

2023-08-31 22:10 UTC, asvae approved these changes

2023-09-01 09:51 UTC, merged