Fix/sidebar fixes
epicmaxco/vuestic-ui pull request #3704
Opened 2023-08-17 10:03 UTC by m0ksem

👋

2023-08-17 10:38 UTC, asvae commented on packages/docs/components/layout/Sidebar.vue
>  @import "@/assets/smart-grid.scss";
Add breaking change to the log.

2023-08-17 22:37 UTC, asvae commented on packages/ui/src/components/va-sidebar/VaSidebar.vue
> -    <div class="va-sidebar__menu" :style="`width: ${computedWidth};`">
Sidebar "right" story is broken (was before your pr as well).

2023-08-17 22:55 UTC, asvae requested changes
Too many stories are broken right now. I see docs are all right, but still.

Not saying we need them perfect (that's something to pursue in stories rework).

2023-08-17 22:55 UTC, asvae commented on packages/ui/src/components/va-sidebar/VaSidebar.vue
> -    <div class="va-sidebar__menu" :style="`width: ${computedWidth};`">
Sidebar "100% width" story is broken (aslwo was before your pr).

<img width="424" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/44facbf1-4c11-47ff-a51b-f8e8ef6db2e6">

2023-08-17 22:55 UTC, asvae commented on packages/ui/src/components/va-sidebar/VaSidebar.vue
> -    <div class="va-sidebar__menu" :style="`width: ${computedWidth};`">
Minimized width story is broken (is less than 25%)

<img width="396" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/d384a3b4-9c62-4bb2-ae80-423cd3585dd0">

2023-08-17 22:55 UTC, asvae commented on packages/ui/src/components/va-sidebar/VaSidebar.vue
> -    <div class="va-sidebar__menu" :style="`width: ${computedWidth};`">
Hoverable minimized story seems to be broken (Should do somethin on hover? right now - does nothing)

<img width="407" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/dd0374a8-f33c-4bab-839b-fa67daae2a56">

2023-08-22 15:23 UTC, m0ksem commented
Because this PR makes breaking changes and all of this generally made for VaLayout component I'll merge this in feat/layout pr and close tihs PR.

2023-08-22 15:23 UTC, closed without merging