Turn ColorCSSVariablesUpdater from demo into story
epicmaxco/vuestic-ui pull request #3979
Opened 2023-10-25 12:51 UTC by xiongmao86

Turn the `ColorCSSVariablesUpdater` from demo into story.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2023-11-03 14:54 UTC, m0ksem requested changes

2023-11-03 14:54 UTC, m0ksem commented on packages/ui/src/services/color/ColorCSSVariablesUpdater.stories.ts
> +    change (color) {
Would be better to have it in script setup. Even though it doesn't produce any memory leaks or other issues it feels weird for me to use hooks in options api.

2023-11-03 14:54 UTC, m0ksem commented on packages/ui/src/services/color/ColorCSSVariablesUpdater.stories.ts
> +      <a class="title title--va-danger">
We test here css variables, I don't remember what is title class and where can I find it... How about we actually use `var(--va-danger)` here and simplify this story?

2023-11-03 14:54 UTC, m0ksem commented on packages/ui/src/services/color/ColorCSSVariablesUpdater.stories.ts
> +    <va-divider />
The style guide for stories is kind of new, I'm not really into it right now, but va-diivder feels redundant here.

2023-11-04 12:39 UTC, xiongmao86 commented on packages/ui/src/services/color/ColorCSSVariablesUpdater.stories.ts
> +      </a>
Hi, @m0ksem, I have changed code according to your comments. I have take another look, in storybook this anchor doesn't show the danger color. I Have no idea why... :(

2023-11-05 03:44 UTC, xiongmao86 commented on packages/ui/src/services/color/ColorCSSVariablesUpdater.stories.ts
> +      </a>
It is a stupid mistake, I reflect on it this morning, turns out I am using class but not style.

2023-11-06 10:34 UTC, m0ksem commented on packages/ui/src/services/color/ColorCSSVariablesUpdater.stories.ts
> +      <va-chip color="danger">This is vue component</va-chip>
Also, this story tests two cases right now: css variable and how component reacts to color config update. Should only test css variables here and test second case somewhere else. (Idk where).

```suggestion
```

2023-11-06 10:34 UTC, m0ksem commented on packages/ui/src/services/color/ColorCSSVariablesUpdater.stories.ts
> +      danger = blue
```suggestion
      blue (#4ab2e3)
```

2023-11-06 10:35 UTC, m0ksem commented on packages/ui/src/services/color/ColorCSSVariablesUpdater.stories.ts
> +      danger = red
We were repeating danger = in text above and button text

```suggestion
      red (#e34b4a)
```

2023-11-06 10:39 UTC, m0ksem commented
Thanks! Story looks much better now!

2023-11-06 10:40 UTC, merged