feat/va-carousel
epicmaxco/vuestic-ui pull request #410
Opened 2020-08-31 15:16 UTC by Kushich

closes #45 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2020-10-20 13:16 UTC, asvae requested changes
Overall looks good, but some small tweaks are needed.

2020-10-20 13:16 UTC, asvae commented on packages/docs/components/page-configs/va-carousel/api-options.ts
> +import { ManualApiOptions } from 'vuestic-ui/src/services/api-docs/ManualApiOptions'
Needs to be more visible: 
![image](https://user-images.githubusercontent.com/5394573/96589753-de3cae80-12ed-11eb-8d6a-badf13100cd3.png)

2020-10-20 13:16 UTC, asvae commented on packages/docs/components/page-configs/va-carousel/api-options.ts
> +import { ManualApiOptions } from 'vuestic-ui/src/services/api-docs/ManualApiOptions'
draggable is kinda easy to break
![2020-10-20_16-05-03](https://user-images.githubusercontent.com/5394573/96589906-0fb57a00-12ee-11eb-96a9-5b84976642ee.gif)

2020-10-20 13:16 UTC, asvae commented on packages/ui/src/components/vuestic-components/va-carousel/VaCarousel.vue
> +      'ms-flex-preferred-size': `${this.c_width}px`,
you can use camelCase here

2020-10-20 13:16 UTC, asvae commented on packages/ui/src/components/vuestic-components/va-carousel/VaCarousel.vue
> +  provide () {
Can you check this works in nuxt?

2020-10-20 13:16 UTC, asvae commented on packages/docs/components/page-configs/va-carousel/page-config.ts
> +  {
We probably can use helpers here, given some other changes are needed.

2021-12-28 09:26 UTC, kushich commented
Outdated OR. It's easier to create a new solution

2021-12-28 09:26 UTC, closed without merging