add aliases for add/remove icons
epicmaxco/vuestic-ui pull request #4129
Opened 2024-01-05 10:03 UTC by VasylHryha

## Description
close https://github.com/epicmaxco/vuestic-ui/issues/4058

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2024-01-05 10:09 UTC, VasylHryha commented
Should we retain the `decreaseIcon` and `increaseIcon` props, or should we completely transition to using `iconConfig` for defining icons in `VaCounter` ?

2024-01-05 18:25 UTC, m0ksem commented
> Should we retain the `decreaseIcon` and `increaseIcon` props, or should we completely transition to using `iconConfig` for defining icons in `VaCounter` ?

We don't do this for other component icons like Select arrow down, Input error icon, Modal close icon. 
We need to make rules how to use icons in a component and then standardize this behavior across all components.

2024-01-05 18:28 UTC, m0ksem requested changes

2024-01-05 18:28 UTC, m0ksem commented on packages/ui/src/components/va-counter/VaCounter.vue
> +import { safeCSSLength } from '@/utils/css'
```suggestion
import { safeCSSLength } from '../../utils/css'
```

We use relative paths only.

2024-01-09 08:28 UTC, VasylHryha commented on packages/ui/src/components/va-counter/VaCounter.vue
> +import { safeCSSLength } from '@/utils/css'
reverted changes

2024-01-10 21:46 UTC, m0ksem approved these changes

2024-01-10 21:46 UTC, merged