fix(VaPopover): Fixed closing other hover popovers on mouse leave
epicmaxco/vuestic-ui pull request #4301
Opened 2024-06-02 11:42 UTC by Fsss126

closes #4250

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2024-06-03 14:37 UTC, m0ksem commented
Looks like we need to check if new item under hover is also dropdown/popover instead of having a prop...

We can utilize useCache and have a property like "dropdown under hover" ID and check if there is another dropdown under hover, we do not move focus.

2024-06-03 14:41 UTC, m0ksem requested changes
Having extra prop doesn't seem as proper solution for me.

2025-01-13 12:08 UTC, zxiest commented
Any update on this guys? This is super annoying

2025-02-05 16:03 UTC, closed without merging

2025-02-05 16:03 UTC, m0ksem commented
This is fixed in dev.