Fixed vaDropdown overflowing issue.
epicmaxco/vuestic-ui pull request #880
Opened 2021-06-23 20:43 UTC by DieselTripleX

## Description

closes #850

1. Fixed overflowing issue for Dropdown component. (It also fixed Popover component overflowing issue, because Popover essentially using Dropdown component)
2. Removed VaPopup from the project.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2021-06-24 14:25 UTC, m0ksem approved these changes

2021-06-25 09:05 UTC, m0ksem requested changes

2021-06-25 09:05 UTC, m0ksem commented on packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
> +  teleportTarget = prop<string>({ type: String, default: '#app' })
Need a better name for this prop. We don't need to use 'teleport' work in this prop name.

2021-06-25 09:28 UTC, m0ksem commented
How about keyboard navigation with this teleport feature?

2021-07-05 10:13 UTC, m0ksem approved these changes

2021-07-15 11:47 UTC, asvae commented on packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
> +  target = prop<string>({ type: String, default: '#app' })
What's this magical `#app`?
Maybe use `body` instead?

We likely want this component to work fine even if there is no `#app`.

2021-07-15 12:04 UTC, asvae commented on packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
> +      <teleport :to="target">
This demo seems to be broken.

![image](https://user-images.githubusercontent.com/5394573/125784939-26fe97c8-6fcf-4492-a1a3-c36be156dc15.png)

There are generally 2 cases we want to cover:
1) User want dropdown to be global.
2) User wants to keep dropdown inside a wrapper (rare case).
If you think we don't have to consider 2nd case at all - please remove it from demo (mb some other places).

2021-07-15 12:06 UTC, asvae commented
Left a couple of points.
Thanks for removing old code!

2021-07-21 10:32 UTC, closed without merging