Added language auto-detection.
epicmaxco/vuestic-ui pull request #913
Opened 2021-07-01 15:05 UTC by DieselTripleX

## Description

Closes #903

Now, DOC's homepage takes local storage/navigator language value as default.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2021-07-05 10:15 UTC, m0ksem approved these changes

2021-07-15 13:08 UTC, asvae commented on packages/docs/src/locales/index.ts
> +export const DEFAULT_LANGUAGE = localStorage.language || window.navigator.language || 'en'
`window.navigator.language` won't work. It uses different format (`en-US`)

2021-07-15 13:08 UTC, asvae requested changes
Needs some changes :).

2021-07-21 11:41 UTC, m0ksem approved these changes

2021-08-05 10:08 UTC, merged