Fixed clipboard button.
epicmaxco/vuestic-ui pull request #933
Opened 2021-07-07 12:07 UTC by DieselTripleX

## Description

Closes #919

Fixed clipboard button, using Clipboard API. Previously, v-clipboard plugin for nuxt was used for copy functional, but we rejected nuxt after moving from vue2 -> vue3.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2021-07-09 12:15 UTC, m0ksem requested changes
As I can see [Clipboard API](https://caniuse.com/mdn-api_clipboard_writetext) has partial support for all browsers. For security reasons, I think.

But, [Clipboard API WriteText](https://caniuse.com/mdn-api_clipboard_writetext) is supported everywhere, except IE 11.

A small change is required.

2021-07-09 12:15 UTC, m0ksem commented on packages/docs/src/components/DocsNavigation.vue
> +        window.navigator.clipboard.writeText(this.code)
According to specification https://w3c.github.io/clipboard-apis/#dom-clipboard-writetext, write text is an async function. You should use `await` here to catch errors.
```suggestion
        await window.navigator.clipboard.writeText(this.code)
```

Can you check if I correct? Maybe this `await` can break your code 😄

2021-07-09 13:13 UTC, m0ksem approved these changes

2021-08-08 11:40 UTC, asvae commented
Thanks!

2021-08-08 11:40 UTC, merged