add selectors for text styles
epicmaxco/vuestic-ui pull request #936
Opened 2021-07-08 06:29 UTC by sergey-kravcov

close #764 

## Description
Added selectors for text styles next colors: "primary", "secondary", "success", "info", "danger", "warning", "gray", "dark".
Rule: --va-[color]
![Снимок экрана 2021-07-07 в 17 24 44](https://user-images.githubusercontent.com/20461547/124873262-e8632200-dfce-11eb-9f8b-ccd6e51a2724.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2021-07-09 12:02 UTC, m0ksem requested changes
Please, prevent conflicts with other frameworks.

Also, there should be few lines in docs about this feature.

2021-07-09 12:02 UTC, m0ksem commented on packages/ui/src/components/vuestic-sass/global/typography.demo.vue
> +      <div v-for="color in textStyleColors" :key="color" :class="`text--${color}`">{{ color }} text</div>
According to https://github.com/epicmaxco/vuestic-ui/issues/876, we should use the `va` prefix in every of our classes. Please, make sure that the feature will not conflict with other frameworks.

2021-07-21 10:40 UTC, m0ksem commented
If I am a user I can define my custom color `--va-strange` via `GlobalConfig > ColorConfig`. CSS variable will be created, but CSS class - not.

2021-07-30 14:14 UTC, sergey-kravcov commented
> If I am a user I can define my custom color `--va-strange` via `GlobalConfig > ColorConfig`. CSS variable will be created, but CSS class - not.

After discussion it was decided to implement in the future

2022-04-29 13:44 UTC, closed without merging