Fix#850/complex solutions
epicmaxco/vuestic-ui pull request #965
Opened 2021-07-21 12:39 UTC by DieselTripleX

## Description

Closes #850!

First of all, merged #859 and #880.
1. Added teleport functional for dropdowns and modals to prevent overflowing.
  1.1 Added <attachElement> prop that responsible for teleport destination selector (Default: "body").
  1.2 Added <disableAttachment> prop that disables teleport feature (In rare cases, might be useful).
2. Removed popover component from the project.
3. Fixed select component styling issue, after teleporting dropdown to DOM root.
4. Changed demo's descripition for incoming fixes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

2021-07-29 09:35 UTC, asvae commented on packages/ui/src/components/vuestic-components/va-modal/VaModal.vue
>  <template>
Nested modal doesn't work correctly.

2021-07-29 09:41 UTC, asvae commented on packages/ui/src/components/vuestic-components/va-modal/VaModal.vue
> +  attachElement = prop<string>({ type: String, default: 'body' })
can we move this to composable file?

2021-07-29 09:50 UTC, asvae commented
Feel free to merge with squash after fix.

2021-07-29 09:52 UTC, asvae approved these changes

2021-07-29 10:06 UTC, DieselTripleX commented on packages/ui/src/components/vuestic-components/va-modal/VaModal.vue
>  <template>
👌 Got it!

2021-08-16 10:28 UTC, m0ksem requested changes
Modal can not be closed. It causes an error inside Vue and then breaks vue-i18n.

![image](https://user-images.githubusercontent.com/23530004/129550002-a6085719-a96e-4cb8-a5a9-02ad0c8bdee1.png)

2021-09-20 16:33 UTC, m0ksem commented
Remade modals a little bit, nested modals work fine now.

2021-09-21 18:43 UTC, m0ksem commented
Docs required here. Also, you don't specify attachment props for VaButtonDropdown and other components that using VaDropdown.

2021-09-21 19:34 UTC, m0ksem commented
I think we can provide `attachElement` prop using VaConfig in some rare cases, so we don't need a special prop to pass to VaDropdown. 

I suppose we can make some service that will allow us to pass props to specific child components later.
For example, we can create a config directive
```vue
<va-select ... v-components-config="{ VaDropdown: { 'close-on-click-outside': false } }" />
```

For now solution will be
```vue
<va-config :components="{ VaDropdown: { 'close-on-click-outside': false } }">
  <va-select ... />
</va-config>
```

Anyway passing props to VaDropdown in some components can be a rare case so we can handle it later.

2021-09-22 18:49 UTC, asvae commented
Thanks!

2021-09-22 18:49 UTC, merged